project_id = "owtcqvefxjncwunhkxdc"

[functions.payment-webhook]
verify_jwt = false

[functions.claim-bonus]
verify_jwt = false

[functions.public-avatars]
verify_jwt = false

[functions.download-invoice]
verify_jwt = false

[functions.freelancer-download]
verify_jwt = false

[functions.freelancer-checkout]
verify_jwt = false

[functions.freelancer-payment-webhook]
verify_jwt = false

[functions.freelancer-payment-status]
verify_jwt = false
